/**
 * Build-time helpers for photos in public/images.
 * `webpVariant` returns the .webp sibling path for a .jpg when one exists
 * (generated by `npm run images`), so components can add a <picture> source
 * without any per-photo configuration.
 */
import { existsSync } from 'node:fs';
import { join } from 'node:path';

export function webpVariant(src: string | undefined): string | undefined {
  if (!src || !/\.jpe?g$/i.test(src)) return undefined;
  const webp = src.replace(/\.jpe?g$/i, '.webp');
  return existsSync(join(process.cwd(), 'public', webp)) ? webp : undefined;
}

/** Path of the `-<width>` variant of a photo, e.g. foo.jpg → foo-800.jpg */
export function sizedVariant(src: string, width: number): string {
  return src.replace(/(\.[a-z0-9]+)$/i, `-${width}$1`);
}
